/*
 * generated by Xtext 2.27.0
 */
package ac.soton.java.barebones2.ui.tests;

import ac.soton.java.barebones2.ui.internal.Barebones2Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class BareBonesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Barebones2Activator.getInstance().getInjector("ac.soton.java.barebones2.BareBones");
	}

}
