/*
 * generated by Xtext 2.27.0
 */
package ac.soton.java.barebones2.ui;

import ac.soton.java.barebones2.ui.internal.Barebones2Activator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BareBonesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Barebones2Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Barebones2Activator activator = Barebones2Activator.getInstance();
		return activator != null ? activator.getInjector(Barebones2Activator.AC_SOTON_JAVA_BAREBONES2_BAREBONES) : null;
	}

}
