/*
 * generated by Xtext 2.27.0
 */
package ac.soton.java.barebones2.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBareBonesScopeProvider extends DelegatingScopeProvider {
}
