/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.barebones2.bareBones;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ac.soton.java.barebones2.bareBones.BareBonesFactory
 * @model kind="package"
 * @generated
 */
public interface BareBonesPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "bareBones";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.soton.ac/java/barebones2/BareBones";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "bareBones";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BareBonesPackage eINSTANCE = ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl.init();

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.ProgramImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.StatementImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.ClearImpl <em>Clear</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.ClearImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getClear()
   * @generated
   */
  int CLEAR = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLEAR__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Clear</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLEAR_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.IncrementImpl <em>Increment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.IncrementImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getIncrement()
   * @generated
   */
  int INCREMENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCREMENT__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Increment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INCREMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.DecrementImpl <em>Decrement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.DecrementImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getDecrement()
   * @generated
   */
  int DECREMENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECREMENT__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Decrement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECREMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.WhileImpl <em>While</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.WhileImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getWhile()
   * @generated
   */
  int WHILE = 5;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE__CONDITION = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE__STATEMENTS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>While</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.OutVariableImpl <em>Out Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.OutVariableImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getOutVariable()
   * @generated
   */
  int OUT_VARIABLE = 6;

  /**
   * The feature id for the '<em><b>Formula</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUT_VARIABLE__FORMULA = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Out Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUT_VARIABLE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.OutStringImpl <em>Out String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.OutStringImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getOutString()
   * @generated
   */
  int OUT_STRING = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUT_STRING__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Out String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUT_STRING_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.InImpl <em>In</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.InImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getIn()
   * @generated
   */
  int IN = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IN__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>In</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IN_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.FormulaImpl <em>Formula</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.FormulaImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getFormula()
   * @generated
   */
  int FORMULA = 9;

  /**
   * The number of structural features of the '<em>Formula</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMULA_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.NumberLiteralImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getNumberLiteral()
   * @generated
   */
  int NUMBER_LITERAL = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL__VALUE = FORMULA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Number Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL_FEATURE_COUNT = FORMULA_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.IdentifierImpl <em>Identifier</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.IdentifierImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getIdentifier()
   * @generated
   */
  int IDENTIFIER = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTIFIER__NAME = FORMULA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Identifier</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTIFIER_FEATURE_COUNT = FORMULA_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.AssociativePredicateImpl <em>Associative Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.AssociativePredicateImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getAssociativePredicate()
   * @generated
   */
  int ASSOCIATIVE_PREDICATE = 12;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATIVE_PREDICATE__LEFT = FORMULA_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Tag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATIVE_PREDICATE__TAG = FORMULA_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATIVE_PREDICATE__RIGHT = FORMULA_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Associative Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATIVE_PREDICATE_FEATURE_COUNT = FORMULA_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.RelationalPredicateImpl <em>Relational Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.RelationalPredicateImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getRelationalPredicate()
   * @generated
   */
  int RELATIONAL_PREDICATE = 13;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_PREDICATE__LEFT = FORMULA_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Tag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_PREDICATE__TAG = FORMULA_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_PREDICATE__RIGHT = FORMULA_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Relational Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_PREDICATE_FEATURE_COUNT = FORMULA_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.AdditionSubtractionImpl <em>Addition Subtraction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.AdditionSubtractionImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getAdditionSubtraction()
   * @generated
   */
  int ADDITION_SUBTRACTION = 14;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_SUBTRACTION__LEFT = FORMULA_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Tag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_SUBTRACTION__TAG = FORMULA_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_SUBTRACTION__RIGHT = FORMULA_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Addition Subtraction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_SUBTRACTION_FEATURE_COUNT = FORMULA_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link ac.soton.java.barebones2.bareBones.impl.MultiplicationDivisionImpl <em>Multiplication Division</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ac.soton.java.barebones2.bareBones.impl.MultiplicationDivisionImpl
   * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getMultiplicationDivision()
   * @generated
   */
  int MULTIPLICATION_DIVISION = 15;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_DIVISION__LEFT = FORMULA_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Tag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_DIVISION__TAG = FORMULA_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_DIVISION__RIGHT = FORMULA_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Multiplication Division</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_DIVISION_FEATURE_COUNT = FORMULA_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see ac.soton.java.barebones2.bareBones.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link ac.soton.java.barebones2.bareBones.Program#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see ac.soton.java.barebones2.bareBones.Program#getStatements()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Statements();

  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see ac.soton.java.barebones2.bareBones.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.Clear <em>Clear</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Clear</em>'.
   * @see ac.soton.java.barebones2.bareBones.Clear
   * @generated
   */
  EClass getClear();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.barebones2.bareBones.Clear#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ac.soton.java.barebones2.bareBones.Clear#getName()
   * @see #getClear()
   * @generated
   */
  EAttribute getClear_Name();

  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.Increment <em>Increment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Increment</em>'.
   * @see ac.soton.java.barebones2.bareBones.Increment
   * @generated
   */
  EClass getIncrement();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.barebones2.bareBones.Increment#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ac.soton.java.barebones2.bareBones.Increment#getName()
   * @see #getIncrement()
   * @generated
   */
  EAttribute getIncrement_Name();

  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.Decrement <em>Decrement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decrement</em>'.
   * @see ac.soton.java.barebones2.bareBones.Decrement
   * @generated
   */
  EClass getDecrement();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.barebones2.bareBones.Decrement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ac.soton.java.barebones2.bareBones.Decrement#getName()
   * @see #getDecrement()
   * @generated
   */
  EAttribute getDecrement_Name();

  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.While <em>While</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While</em>'.
   * @see ac.soton.java.barebones2.bareBones.While
   * @generated
   */
  EClass getWhile();

  /**
   * Returns the meta object for the containment reference '{@link ac.soton.java.barebones2.bareBones.While#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see ac.soton.java.barebones2.bareBones.While#getCondition()
   * @see #getWhile()
   * @generated
   */
  EReference getWhile_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link ac.soton.java.barebones2.bareBones.While#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see ac.soton.java.barebones2.bareBones.While#getStatements()
   * @see #getWhile()
   * @generated
   */
  EReference getWhile_Statements();

  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.OutVariable <em>Out Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Out Variable</em>'.
   * @see ac.soton.java.barebones2.bareBones.OutVariable
   * @generated
   */
  EClass getOutVariable();

  /**
   * Returns the meta object for the containment reference '{@link ac.soton.java.barebones2.bareBones.OutVariable#getFormula <em>Formula</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Formula</em>'.
   * @see ac.soton.java.barebones2.bareBones.OutVariable#getFormula()
   * @see #getOutVariable()
   * @generated
   */
  EReference getOutVariable_Formula();

  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.OutString <em>Out String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Out String</em>'.
   * @see ac.soton.java.barebones2.bareBones.OutString
   * @generated
   */
  EClass getOutString();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.barebones2.bareBones.OutString#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ac.soton.java.barebones2.bareBones.OutString#getName()
   * @see #getOutString()
   * @generated
   */
  EAttribute getOutString_Name();

  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.In <em>In</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>In</em>'.
   * @see ac.soton.java.barebones2.bareBones.In
   * @generated
   */
  EClass getIn();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.barebones2.bareBones.In#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ac.soton.java.barebones2.bareBones.In#getName()
   * @see #getIn()
   * @generated
   */
  EAttribute getIn_Name();

  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.Formula <em>Formula</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Formula</em>'.
   * @see ac.soton.java.barebones2.bareBones.Formula
   * @generated
   */
  EClass getFormula();

  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.NumberLiteral <em>Number Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Literal</em>'.
   * @see ac.soton.java.barebones2.bareBones.NumberLiteral
   * @generated
   */
  EClass getNumberLiteral();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.barebones2.bareBones.NumberLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see ac.soton.java.barebones2.bareBones.NumberLiteral#getValue()
   * @see #getNumberLiteral()
   * @generated
   */
  EAttribute getNumberLiteral_Value();

  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.Identifier <em>Identifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Identifier</em>'.
   * @see ac.soton.java.barebones2.bareBones.Identifier
   * @generated
   */
  EClass getIdentifier();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.barebones2.bareBones.Identifier#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ac.soton.java.barebones2.bareBones.Identifier#getName()
   * @see #getIdentifier()
   * @generated
   */
  EAttribute getIdentifier_Name();

  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.AssociativePredicate <em>Associative Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Associative Predicate</em>'.
   * @see ac.soton.java.barebones2.bareBones.AssociativePredicate
   * @generated
   */
  EClass getAssociativePredicate();

  /**
   * Returns the meta object for the containment reference '{@link ac.soton.java.barebones2.bareBones.AssociativePredicate#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see ac.soton.java.barebones2.bareBones.AssociativePredicate#getLeft()
   * @see #getAssociativePredicate()
   * @generated
   */
  EReference getAssociativePredicate_Left();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.barebones2.bareBones.AssociativePredicate#getTag <em>Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tag</em>'.
   * @see ac.soton.java.barebones2.bareBones.AssociativePredicate#getTag()
   * @see #getAssociativePredicate()
   * @generated
   */
  EAttribute getAssociativePredicate_Tag();

  /**
   * Returns the meta object for the containment reference '{@link ac.soton.java.barebones2.bareBones.AssociativePredicate#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see ac.soton.java.barebones2.bareBones.AssociativePredicate#getRight()
   * @see #getAssociativePredicate()
   * @generated
   */
  EReference getAssociativePredicate_Right();

  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.RelationalPredicate <em>Relational Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relational Predicate</em>'.
   * @see ac.soton.java.barebones2.bareBones.RelationalPredicate
   * @generated
   */
  EClass getRelationalPredicate();

  /**
   * Returns the meta object for the containment reference '{@link ac.soton.java.barebones2.bareBones.RelationalPredicate#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see ac.soton.java.barebones2.bareBones.RelationalPredicate#getLeft()
   * @see #getRelationalPredicate()
   * @generated
   */
  EReference getRelationalPredicate_Left();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.barebones2.bareBones.RelationalPredicate#getTag <em>Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tag</em>'.
   * @see ac.soton.java.barebones2.bareBones.RelationalPredicate#getTag()
   * @see #getRelationalPredicate()
   * @generated
   */
  EAttribute getRelationalPredicate_Tag();

  /**
   * Returns the meta object for the containment reference '{@link ac.soton.java.barebones2.bareBones.RelationalPredicate#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see ac.soton.java.barebones2.bareBones.RelationalPredicate#getRight()
   * @see #getRelationalPredicate()
   * @generated
   */
  EReference getRelationalPredicate_Right();

  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.AdditionSubtraction <em>Addition Subtraction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition Subtraction</em>'.
   * @see ac.soton.java.barebones2.bareBones.AdditionSubtraction
   * @generated
   */
  EClass getAdditionSubtraction();

  /**
   * Returns the meta object for the containment reference '{@link ac.soton.java.barebones2.bareBones.AdditionSubtraction#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see ac.soton.java.barebones2.bareBones.AdditionSubtraction#getLeft()
   * @see #getAdditionSubtraction()
   * @generated
   */
  EReference getAdditionSubtraction_Left();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.barebones2.bareBones.AdditionSubtraction#getTag <em>Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tag</em>'.
   * @see ac.soton.java.barebones2.bareBones.AdditionSubtraction#getTag()
   * @see #getAdditionSubtraction()
   * @generated
   */
  EAttribute getAdditionSubtraction_Tag();

  /**
   * Returns the meta object for the containment reference '{@link ac.soton.java.barebones2.bareBones.AdditionSubtraction#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see ac.soton.java.barebones2.bareBones.AdditionSubtraction#getRight()
   * @see #getAdditionSubtraction()
   * @generated
   */
  EReference getAdditionSubtraction_Right();

  /**
   * Returns the meta object for class '{@link ac.soton.java.barebones2.bareBones.MultiplicationDivision <em>Multiplication Division</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication Division</em>'.
   * @see ac.soton.java.barebones2.bareBones.MultiplicationDivision
   * @generated
   */
  EClass getMultiplicationDivision();

  /**
   * Returns the meta object for the containment reference '{@link ac.soton.java.barebones2.bareBones.MultiplicationDivision#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see ac.soton.java.barebones2.bareBones.MultiplicationDivision#getLeft()
   * @see #getMultiplicationDivision()
   * @generated
   */
  EReference getMultiplicationDivision_Left();

  /**
   * Returns the meta object for the attribute '{@link ac.soton.java.barebones2.bareBones.MultiplicationDivision#getTag <em>Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tag</em>'.
   * @see ac.soton.java.barebones2.bareBones.MultiplicationDivision#getTag()
   * @see #getMultiplicationDivision()
   * @generated
   */
  EAttribute getMultiplicationDivision_Tag();

  /**
   * Returns the meta object for the containment reference '{@link ac.soton.java.barebones2.bareBones.MultiplicationDivision#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see ac.soton.java.barebones2.bareBones.MultiplicationDivision#getRight()
   * @see #getMultiplicationDivision()
   * @generated
   */
  EReference getMultiplicationDivision_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BareBonesFactory getBareBonesFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.ProgramImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__STATEMENTS = eINSTANCE.getProgram_Statements();

    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.StatementImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.ClearImpl <em>Clear</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.ClearImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getClear()
     * @generated
     */
    EClass CLEAR = eINSTANCE.getClear();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLEAR__NAME = eINSTANCE.getClear_Name();

    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.IncrementImpl <em>Increment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.IncrementImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getIncrement()
     * @generated
     */
    EClass INCREMENT = eINSTANCE.getIncrement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INCREMENT__NAME = eINSTANCE.getIncrement_Name();

    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.DecrementImpl <em>Decrement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.DecrementImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getDecrement()
     * @generated
     */
    EClass DECREMENT = eINSTANCE.getDecrement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECREMENT__NAME = eINSTANCE.getDecrement_Name();

    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.WhileImpl <em>While</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.WhileImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getWhile()
     * @generated
     */
    EClass WHILE = eINSTANCE.getWhile();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE__CONDITION = eINSTANCE.getWhile_Condition();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE__STATEMENTS = eINSTANCE.getWhile_Statements();

    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.OutVariableImpl <em>Out Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.OutVariableImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getOutVariable()
     * @generated
     */
    EClass OUT_VARIABLE = eINSTANCE.getOutVariable();

    /**
     * The meta object literal for the '<em><b>Formula</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUT_VARIABLE__FORMULA = eINSTANCE.getOutVariable_Formula();

    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.OutStringImpl <em>Out String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.OutStringImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getOutString()
     * @generated
     */
    EClass OUT_STRING = eINSTANCE.getOutString();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUT_STRING__NAME = eINSTANCE.getOutString_Name();

    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.InImpl <em>In</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.InImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getIn()
     * @generated
     */
    EClass IN = eINSTANCE.getIn();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IN__NAME = eINSTANCE.getIn_Name();

    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.FormulaImpl <em>Formula</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.FormulaImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getFormula()
     * @generated
     */
    EClass FORMULA = eINSTANCE.getFormula();

    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.NumberLiteralImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getNumberLiteral()
     * @generated
     */
    EClass NUMBER_LITERAL = eINSTANCE.getNumberLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER_LITERAL__VALUE = eINSTANCE.getNumberLiteral_Value();

    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.IdentifierImpl <em>Identifier</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.IdentifierImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getIdentifier()
     * @generated
     */
    EClass IDENTIFIER = eINSTANCE.getIdentifier();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IDENTIFIER__NAME = eINSTANCE.getIdentifier_Name();

    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.AssociativePredicateImpl <em>Associative Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.AssociativePredicateImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getAssociativePredicate()
     * @generated
     */
    EClass ASSOCIATIVE_PREDICATE = eINSTANCE.getAssociativePredicate();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSOCIATIVE_PREDICATE__LEFT = eINSTANCE.getAssociativePredicate_Left();

    /**
     * The meta object literal for the '<em><b>Tag</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSOCIATIVE_PREDICATE__TAG = eINSTANCE.getAssociativePredicate_Tag();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSOCIATIVE_PREDICATE__RIGHT = eINSTANCE.getAssociativePredicate_Right();

    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.RelationalPredicateImpl <em>Relational Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.RelationalPredicateImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getRelationalPredicate()
     * @generated
     */
    EClass RELATIONAL_PREDICATE = eINSTANCE.getRelationalPredicate();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONAL_PREDICATE__LEFT = eINSTANCE.getRelationalPredicate_Left();

    /**
     * The meta object literal for the '<em><b>Tag</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RELATIONAL_PREDICATE__TAG = eINSTANCE.getRelationalPredicate_Tag();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONAL_PREDICATE__RIGHT = eINSTANCE.getRelationalPredicate_Right();

    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.AdditionSubtractionImpl <em>Addition Subtraction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.AdditionSubtractionImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getAdditionSubtraction()
     * @generated
     */
    EClass ADDITION_SUBTRACTION = eINSTANCE.getAdditionSubtraction();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION_SUBTRACTION__LEFT = eINSTANCE.getAdditionSubtraction_Left();

    /**
     * The meta object literal for the '<em><b>Tag</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDITION_SUBTRACTION__TAG = eINSTANCE.getAdditionSubtraction_Tag();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION_SUBTRACTION__RIGHT = eINSTANCE.getAdditionSubtraction_Right();

    /**
     * The meta object literal for the '{@link ac.soton.java.barebones2.bareBones.impl.MultiplicationDivisionImpl <em>Multiplication Division</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ac.soton.java.barebones2.bareBones.impl.MultiplicationDivisionImpl
     * @see ac.soton.java.barebones2.bareBones.impl.BareBonesPackageImpl#getMultiplicationDivision()
     * @generated
     */
    EClass MULTIPLICATION_DIVISION = eINSTANCE.getMultiplicationDivision();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION_DIVISION__LEFT = eINSTANCE.getMultiplicationDivision_Left();

    /**
     * The meta object literal for the '<em><b>Tag</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICATION_DIVISION__TAG = eINSTANCE.getMultiplicationDivision_Tag();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION_DIVISION__RIGHT = eINSTANCE.getMultiplicationDivision_Right();

  }

} //BareBonesPackage
