/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.barebones2.bareBones;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Increment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ac.soton.java.barebones2.bareBones.Increment#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see ac.soton.java.barebones2.bareBones.BareBonesPackage#getIncrement()
 * @model
 * @generated
 */
public interface Increment extends Statement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ac.soton.java.barebones2.bareBones.BareBonesPackage#getIncrement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ac.soton.java.barebones2.bareBones.Increment#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Increment
