/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.barebones2.bareBones;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiplication Division</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ac.soton.java.barebones2.bareBones.MultiplicationDivision#getLeft <em>Left</em>}</li>
 *   <li>{@link ac.soton.java.barebones2.bareBones.MultiplicationDivision#getTag <em>Tag</em>}</li>
 *   <li>{@link ac.soton.java.barebones2.bareBones.MultiplicationDivision#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see ac.soton.java.barebones2.bareBones.BareBonesPackage#getMultiplicationDivision()
 * @model
 * @generated
 */
public interface MultiplicationDivision extends Formula
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Formula)
   * @see ac.soton.java.barebones2.bareBones.BareBonesPackage#getMultiplicationDivision_Left()
   * @model containment="true"
   * @generated
   */
  Formula getLeft();

  /**
   * Sets the value of the '{@link ac.soton.java.barebones2.bareBones.MultiplicationDivision#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Formula value);

  /**
   * Returns the value of the '<em><b>Tag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tag</em>' attribute.
   * @see #setTag(String)
   * @see ac.soton.java.barebones2.bareBones.BareBonesPackage#getMultiplicationDivision_Tag()
   * @model
   * @generated
   */
  String getTag();

  /**
   * Sets the value of the '{@link ac.soton.java.barebones2.bareBones.MultiplicationDivision#getTag <em>Tag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tag</em>' attribute.
   * @see #getTag()
   * @generated
   */
  void setTag(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Formula)
   * @see ac.soton.java.barebones2.bareBones.BareBonesPackage#getMultiplicationDivision_Right()
   * @model containment="true"
   * @generated
   */
  Formula getRight();

  /**
   * Sets the value of the '{@link ac.soton.java.barebones2.bareBones.MultiplicationDivision#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Formula value);

} // MultiplicationDivision
