/**
 * generated by Xtext 2.27.0
 */
package ac.soton.java.barebones2.bareBones;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>While</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ac.soton.java.barebones2.bareBones.While#getCondition <em>Condition</em>}</li>
 *   <li>{@link ac.soton.java.barebones2.bareBones.While#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see ac.soton.java.barebones2.bareBones.BareBonesPackage#getWhile()
 * @model
 * @generated
 */
public interface While extends Statement
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Formula)
   * @see ac.soton.java.barebones2.bareBones.BareBonesPackage#getWhile_Condition()
   * @model containment="true"
   * @generated
   */
  Formula getCondition();

  /**
   * Sets the value of the '{@link ac.soton.java.barebones2.bareBones.While#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Formula value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link ac.soton.java.barebones2.bareBones.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see ac.soton.java.barebones2.bareBones.BareBonesPackage#getWhile_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

} // While
